services:
  - type: web
    name: engineer-adam-hotspot
    env: python
    plan: free
    region: singapore # 150Gbps സിംഗപ്പൂർ ബാക്ക്ബോൺ കിട്ടാൻ ഇത് മസ്റ്റ്!
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
